server:
  port: 8888
spring:
  webflux:
    base-path: /api
  r2dbc:
    url: r2dbc:mysql://172.22.181.26:3306/test-platform?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
logging:
  level:
    org.springframework.r2dbc: DEBUG