server:
  port: 8080
spring:
  webflux:
    base-path: /rest
  r2dbc:
    url: r2dbc:mysql://mysql:3306/test-platform?useUnicode=true&characterEncoding=utf8
    username: root
    password: root123
  data:
    redis:
      host: redis
      port: 6379
      client-name: test-platform
logging:
  level:
    org.springframework.r2dbc: DEBUG